import type { BusOffer, FlightOffer, HotelOffer, PackageOffer } from "./types";

export const flights: FlightOffer[] = [
  {
    kind: "flight",
    id: "tk-ist-ebl",
    from: "istanbul",
    to: "erbil",
    airline: "Turkish Airlines",
    flightNo: "TK 308",
    depart: "01:20",
    arrive: "04:35",
    durationMin: 135,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 312 },
      { source: "Wego", usd: 298 },
      { source: "Almosafer", usd: 305 },
    ],
  },
  {
    kind: "flight",
    id: "tk-ebl-ist",
    from: "erbil",
    to: "istanbul",
    airline: "Turkish Airlines",
    flightNo: "TK 309",
    depart: "05:40",
    arrive: "08:00",
    durationMin: 140,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 318 },
      { source: "Wego", usd: 304 },
    ],
  },
  {
    kind: "flight",
    id: "pc-ist-ebl",
    from: "istanbul",
    to: "erbil",
    airline: "Pegasus",
    flightNo: "PC 816",
    depart: "23:45",
    arrive: "03:05",
    durationMin: 140,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 196 },
      { source: "Skyscanner", usd: 189 },
      { source: "Wego", usd: 192 },
    ],
  },
  {
    kind: "flight",
    id: "fz-dxb-ebl",
    from: "dubai",
    to: "erbil",
    airline: "flydubai",
    flightNo: "FZ 211",
    depart: "09:40",
    arrive: "11:55",
    durationMin: 195,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 214 },
      { source: "Wego", usd: 208 },
      { source: "Almosafer", usd: 211 },
    ],
  },
  {
    kind: "flight",
    id: "qr-doh-ebl",
    from: "doha",
    to: "erbil",
    airline: "Qatar Airways",
    flightNo: "QR 442",
    depart: "08:15",
    arrive: "11:05",
    durationMin: 170,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 341 },
      { source: "Wego", usd: 329 },
      { source: "Kayak", usd: 334 },
    ],
  },
  {
    kind: "flight",
    id: "ia-bgw-ebl",
    from: "baghdad",
    to: "erbil",
    airline: "Iraqi Airways",
    flightNo: "IA 901",
    depart: "07:30",
    arrive: "08:35",
    durationMin: 65,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 98 },
      { source: "Wego", usd: 104 },
    ],
  },
  {
    kind: "flight",
    id: "ia-ebl-bgw",
    from: "erbil",
    to: "baghdad",
    airline: "Iraqi Airways",
    flightNo: "IA 902",
    depart: "18:10",
    arrive: "19:15",
    durationMin: 65,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 96 },
      { source: "Wego", usd: 101 },
    ],
  },
  {
    kind: "flight",
    id: "pc-ist-isu",
    from: "istanbul",
    to: "sulaymaniyah",
    airline: "Pegasus",
    flightNo: "PC 820",
    depart: "22:50",
    arrive: "02:20",
    durationMin: 150,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 214 },
      { source: "Skyscanner", usd: 206 },
    ],
  },
  {
    kind: "flight",
    id: "tk-ist-bgw",
    from: "istanbul",
    to: "baghdad",
    airline: "Turkish Airlines",
    flightNo: "TK 304",
    depart: "00:55",
    arrive: "04:40",
    durationMin: 165,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 287 },
      { source: "Wego", usd: 274 },
      { source: "Almosafer", usd: 281 },
    ],
  },
  {
    kind: "flight",
    id: "ek-dxb-bgw",
    from: "dubai",
    to: "baghdad",
    airline: "Emirates",
    flightNo: "EK 943",
    depart: "10:05",
    arrive: "11:35",
    durationMin: 150,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 356 },
      { source: "Wego", usd: 342 },
    ],
  },
  {
    kind: "flight",
    id: "fz-dxb-njf",
    from: "dubai",
    to: "najaf",
    airline: "flydubai",
    flightNo: "FZ 223",
    depart: "07:20",
    arrive: "08:55",
    durationMin: 155,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 188 },
      { source: "Almosafer", usd: 181 },
      { source: "Wego", usd: 184 },
    ],
  },
  {
    kind: "flight",
    id: "ia-dxb-bsr",
    from: "dubai",
    to: "basra",
    airline: "flydubai",
    flightNo: "FZ 205",
    depart: "13:40",
    arrive: "14:50",
    durationMin: 130,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 172 },
      { source: "Wego", usd: 166 },
    ],
  },
  {
    kind: "flight",
    id: "rj-amm-ebl",
    from: "amman",
    to: "erbil",
    airline: "Royal Jordanian",
    flightNo: "RJ 822",
    depart: "11:30",
    arrive: "13:40",
    durationMin: 130,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 248 },
      { source: "Wego", usd: 239 },
    ],
  },
  {
    kind: "flight",
    id: "rj-ebl-amm",
    from: "erbil",
    to: "amman",
    airline: "Royal Jordanian",
    flightNo: "RJ 823",
    depart: "14:50",
    arrive: "17:00",
    durationMin: 130,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 252 },
      { source: "Wego", usd: 241 },
    ],
  },
  {
    kind: "flight",
    id: "rj-bgw-amm",
    from: "baghdad",
    to: "amman",
    airline: "Royal Jordanian",
    flightNo: "RJ 811",
    depart: "17:20",
    arrive: "19:10",
    durationMin: 110,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 229 },
      { source: "Wego", usd: 221 },
    ],
  },
  {
    kind: "flight",
    id: "rj-amm-bgw",
    from: "amman",
    to: "baghdad",
    airline: "Royal Jordanian",
    flightNo: "RJ 810",
    depart: "14:10",
    arrive: "16:00",
    durationMin: 110,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 226 },
      { source: "Wego", usd: 219 },
    ],
  },
  {
    kind: "flight",
    id: "lh-fra-ebl",
    from: "frankfurt",
    to: "erbil",
    airline: "Lufthansa",
    flightNo: "LH 620",
    depart: "16:55",
    arrive: "23:10",
    durationMin: 255,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 518 },
      { source: "Kayak", usd: 496 },
    ],
  },
  {
    kind: "flight",
    id: "if-ebl-bgw",
    from: "erbil",
    to: "baghdad",
    airline: "Fly Baghdad",
    flightNo: "IF 401",
    depart: "09:15",
    arrive: "10:20",
    durationMin: 65,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 89 },
      { source: "Wego", usd: 94 },
    ],
  },
  {
    kind: "flight",
    id: "ia-bgw-njf",
    from: "baghdad",
    to: "najaf",
    airline: "Iraqi Airways",
    flightNo: "IA 330",
    depart: "08:00",
    arrive: "08:45",
    durationMin: 45,
    stops: 0,
    cabin: "economy",
    sources: [{ source: "Airline", usd: 64 }],
  },
  {
    kind: "flight",
    id: "ia-bgw-bsr",
    from: "baghdad",
    to: "basra",
    airline: "Iraqi Airways",
    flightNo: "IA 201",
    depart: "06:50",
    arrive: "08:00",
    durationMin: 70,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 78 },
      { source: "Wego", usd: 82 },
    ],
  },
  {
    kind: "flight",
    id: "tk-lhr-ebl",
    from: "london",
    to: "erbil",
    airline: "Turkish Airlines",
    flightNo: "TK 1982",
    depart: "16:30",
    arrive: "04:35",
    durationMin: 545,
    stops: 1,
    via: "Istanbul",
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 542 },
      { source: "Skyscanner", usd: 498 },
      { source: "Kayak", usd: 511 },
    ],
  },
  {
    kind: "flight",
    id: "qr-lhr-bgw",
    from: "london",
    to: "baghdad",
    airline: "Qatar Airways",
    flightNo: "QR 4",
    depart: "08:05",
    arrive: "21:40",
    durationMin: 635,
    stops: 1,
    via: "Doha",
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 612 },
      { source: "Wego", usd: 574 },
    ],
  },
  {
    kind: "flight",
    id: "ms-cai-bgw",
    from: "cairo",
    to: "baghdad",
    airline: "EgyptAir",
    flightNo: "MS 680",
    depart: "12:20",
    arrive: "15:35",
    durationMin: 195,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 268 },
      { source: "Wego", usd: 255 },
    ],
  },
  {
    kind: "flight",
    id: "ku-kwi-bsr",
    from: "kuwait",
    to: "basra",
    airline: "Kuwait Airways",
    flightNo: "KU 501",
    depart: "09:00",
    arrive: "10:10",
    durationMin: 70,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 142 },
      { source: "Almosafer", usd: 136 },
    ],
  },
  {
    kind: "flight",
    id: "if-ebl-isu",
    from: "erbil",
    to: "sulaymaniyah",
    airline: "Iraqi Airways",
    flightNo: "IA 955",
    depart: "15:40",
    arrive: "16:20",
    durationMin: 40,
    stops: 0,
    cabin: "economy",
    sources: [{ source: "Airline", usd: 72 }],
  },
  {
    kind: "flight",
    id: "tk-ist-ebl-biz",
    from: "istanbul",
    to: "erbil",
    airline: "Turkish Airlines",
    flightNo: "TK 306",
    depart: "12:40",
    arrive: "15:55",
    durationMin: 135,
    stops: 0,
    cabin: "business",
    sources: [
      { source: "Airline", usd: 786 },
      { source: "Wego", usd: 754 },
    ],
  },
  {
    kind: "flight",
    id: "me-bey-ebl",
    from: "beirut",
    to: "erbil",
    airline: "Middle East Airlines",
    flightNo: "ME 325",
    depart: "10:50",
    arrive: "13:15",
    durationMin: 145,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 276 },
      { source: "Wego", usd: 268 },
    ],
  },
  {
    kind: "flight",
    id: "tk-ist-ika",
    from: "istanbul",
    to: "tehran",
    airline: "Turkish Airlines",
    flightNo: "TK 872",
    depart: "01:10",
    arrive: "05:20",
    durationMin: 190,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 198 },
      { source: "Wego", usd: 189 },
    ],
  },
  {
    kind: "flight",
    id: "fz-dxb-del",
    from: "dubai",
    to: "delhi",
    airline: "flydubai",
    flightNo: "FZ 445",
    depart: "10:20",
    arrive: "15:10",
    durationMin: 200,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 164 },
      { source: "Wego", usd: 158 },
    ],
  },
  {
    kind: "flight",
    id: "qr-doh-del",
    from: "doha",
    to: "delhi",
    airline: "Qatar Airways",
    flightNo: "QR 578",
    depart: "02:15",
    arrive: "08:05",
    durationMin: 200,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 241 },
      { source: "Kayak", usd: 233 },
    ],
  },
  {
    kind: "flight",
    id: "ek-dxb-maa",
    from: "dubai",
    to: "chennai",
    airline: "Emirates",
    flightNo: "EK 542",
    depart: "09:05",
    arrive: "14:40",
    durationMin: 215,
    stops: 0,
    cabin: "economy",
    sources: [
      { source: "Airline", usd: 188 },
      { source: "Wego", usd: 181 },
    ],
  },
];

export const hotels: HotelOffer[] = [
  {
    kind: "hotel",
    id: "divan-erbil",
    city: "erbil",
    name: "Divan Erbil",
    area: "Downtown / Ankawa road",
    stars: 5,
    rating: 8.7,
    reviews: 2140,
    nightlyUsd: 168,
    amenities: ["Pool", "Spa", "Airport transfer"],
    note: "Reliable five-star for first nights after a late EBL arrival.",
  },
  {
    kind: "hotel",
    id: "rotana-erbil",
    city: "erbil",
    name: "Erbil Rotana",
    area: "Gulan Street",
    stars: 5,
    rating: 8.4,
    reviews: 1688,
    nightlyUsd: 142,
    amenities: ["Gym", "Restaurant", "Parking"],
    note: "Business-district base with easy taxi access to the citadel.",
  },
  {
    kind: "hotel",
    id: "erbil-view",
    city: "erbil",
    name: "Erbil View Hotel",
    area: "Citadel rim",
    stars: 4,
    rating: 8.1,
    reviews: 940,
    nightlyUsd: 78,
    amenities: ["Breakfast", "City view"],
    note: "Walkable to the bazaar if you want the old city at street level.",
  },
  {
    kind: "hotel",
    id: "ankawa-residence",
    city: "erbil",
    name: "Ankawa Residence",
    area: "Ankawa",
    stars: 3,
    rating: 8.0,
    reviews: 512,
    nightlyUsd: 52,
    amenities: ["Kitchenette", "Wifi"],
    note: "Quiet Christian quarter, restaurants stay open later.",
  },
  {
    kind: "hotel",
    id: "khan-saray",
    city: "sulaymaniyah",
    name: "Khan Saray Hotel",
    area: "Salim Street",
    stars: 4,
    rating: 8.3,
    reviews: 776,
    nightlyUsd: 64,
    amenities: ["Breakfast", "Central"],
    note: "The usual first pick — close to cafes and the bazaar.",
  },
  {
    kind: "hotel",
    id: "grand-millennium-slemani",
    city: "sulaymaniyah",
    name: "Grand Millennium Sulaimani",
    area: "Bakhtyari",
    stars: 5,
    rating: 8.6,
    reviews: 1204,
    nightlyUsd: 128,
    amenities: ["Pool", "Spa", "Club lounge"],
    note: "Hillside five-star with the cleanest rooms in the city.",
  },
  {
    kind: "hotel",
    id: "ramada-slemani",
    city: "sulaymaniyah",
    name: "Ramada Sulaimaniya",
    area: "Salim Street",
    stars: 4,
    rating: 7.9,
    reviews: 633,
    nightlyUsd: 71,
    amenities: ["Gym", "Restaurant"],
    note: "Straightforward mid-range on the main drag.",
  },
  {
    kind: "hotel",
    id: "cristal-duhok",
    city: "duhok",
    name: "Cristal Hotel Duhok",
    area: "City center",
    stars: 4,
    rating: 8.2,
    reviews: 410,
    nightlyUsd: 58,
    amenities: ["Breakfast", "Parking"],
    note: "Best all-rounder if you are heading north to Amedi.",
  },
  {
    kind: "hotel",
    id: "jiyan-duhok",
    city: "duhok",
    name: "Jiyan Hotel",
    area: "Malta",
    stars: 3,
    rating: 7.8,
    reviews: 266,
    nightlyUsd: 42,
    amenities: ["Wifi", "Airport taxi"],
    note: "Simple, clean, and used to independent travelers.",
  },
  {
    kind: "hotel",
    id: "babylon-rotana",
    city: "baghdad",
    name: "Babylon Rotana",
    area: "Al-Jadriya",
    stars: 5,
    rating: 8.5,
    reviews: 1882,
    nightlyUsd: 176,
    amenities: ["River view", "Pool", "Security"],
    note: "The established five-star on the Tigris.",
  },
  {
    kind: "hotel",
    id: "taj-baghdad",
    city: "baghdad",
    name: "The Taj Hotel",
    area: "Karada",
    stars: 5,
    rating: 8.3,
    reviews: 954,
    nightlyUsd: 154,
    amenities: ["Restaurant", "Gym"],
    note: "Strong reviews, easier restaurant access than the Green Zone.",
  },
  {
    kind: "hotel",
    id: "coral-baghdad",
    city: "baghdad",
    name: "Coral Baghdad Hotel",
    area: "Al-Mansour",
    stars: 4,
    rating: 7.9,
    reviews: 701,
    nightlyUsd: 88,
    amenities: ["Breakfast", "Parking"],
    note: "Solid mid-range in a neighborhood with shops.",
  },
  {
    kind: "hotel",
    id: "inter-baghdad",
    city: "baghdad",
    name: "Inter Hotel",
    area: "Karrada Dakhil",
    stars: 3,
    rating: 7.6,
    reviews: 388,
    nightlyUsd: 54,
    amenities: ["Wifi", "Breakfast"],
    note: "The practical mid-range used by independent visitors.",
  },
  {
    kind: "hotel",
    id: "qasr-aldur",
    city: "najaf",
    name: "Qasr AlDur Hotel",
    area: "Old city",
    stars: 5,
    rating: 8.4,
    reviews: 612,
    nightlyUsd: 198,
    amenities: ["Shrine access", "Restaurant"],
    note: "Premium stay near the shrine; book early around Arbaeen.",
  },
  {
    kind: "hotel",
    id: "barada-najaf",
    city: "najaf",
    name: "Barada Hotel Najaf",
    area: "City center",
    stars: 3,
    rating: 7.7,
    reviews: 290,
    nightlyUsd: 46,
    amenities: ["Wifi", "Breakfast"],
    note: "Simple pilgrim hotel — walkable, no extras.",
  },
  {
    kind: "hotel",
    id: "shams-basra",
    city: "basra",
    name: "Shams Al-Basra",
    area: "Corniche",
    stars: 4,
    rating: 8.0,
    reviews: 444,
    nightlyUsd: 72,
    amenities: ["River view", "Restaurant"],
    note: "The easiest first night after a BSR landing.",
  },
  {
    kind: "hotel",
    id: "basra-international",
    city: "basra",
    name: "Basra International Hotel",
    area: "Ashar",
    stars: 5,
    rating: 8.1,
    reviews: 518,
    nightlyUsd: 134,
    amenities: ["Pool", "Gym", "Business center"],
    note: "Older five-star, still the city’s formal address.",
  },
  {
    kind: "hotel",
    id: "al-taawon-karbala",
    city: "karbala",
    name: "Al Taawon Hotel",
    area: "Between the two shrines",
    stars: 3,
    rating: 7.8,
    reviews: 802,
    nightlyUsd: 61,
    amenities: ["Walking distance", "Breakfast"],
    note: "Rates jump sharply in Muharram and Arbaeen.",
  },
  {
    kind: "hotel",
    id: "nineveh-mosul",
    city: "mosul",
    name: "Nineveh International",
    area: "Left bank",
    stars: 4,
    rating: 7.5,
    reviews: 196,
    nightlyUsd: 68,
    amenities: ["Generator", "Restaurant"],
    note: "Limited online inventory — confirm the night before.",
  },
  {
    kind: "hotel",
    id: "shaqlawa-palace",
    city: "shaqlawa",
    name: "Shaqlawa Palace Hotel",
    area: "Town ridge",
    stars: 4,
    rating: 8.0,
    reviews: 318,
    nightlyUsd: 74,
    amenities: ["Terrace", "Breakfast", "Parking"],
    note: "The usual Friday-night hotel if you do not want a villa.",
  },
  {
    kind: "hotel",
    id: "korek-resort",
    city: "korek",
    name: "Korek Mountain Resort",
    area: "Ridge",
    stars: 4,
    rating: 7.9,
    reviews: 540,
    nightlyUsd: 118,
    amenities: ["Cable car", "Chalet rooms", "Restaurant"],
    note: "Stay on the ridge. Confirm the lift is running before you book the night.",
  },
  {
    kind: "hotel",
    id: "dukan-lake-hotel",
    city: "dukan",
    name: "Dukan Lake Hotel",
    area: "Shore",
    stars: 3,
    rating: 7.6,
    reviews: 204,
    nightlyUsd: 56,
    amenities: ["Lake view", "Parking"],
    note: "Hotel if the villa brokers are full. Friday nights go first.",
  },
];

export const buses: BusOffer[] = [
  {
    kind: "bus",
    id: "cihan-ebl-isu",
    from: "erbil",
    to: "sulaymaniyah",
    operator: "Erbil East Terminal",
    depart: "08:00",
    arrive: "11:10",
    durationMin: 190,
    seat: "VIP coach",
    sources: [
      { source: "Station", usd: 14 },
      { source: "Gesht", usd: 16 },
    ],
  },
  {
    kind: "bus",
    id: "kr-ebl-isu",
    from: "erbil",
    to: "sulaymaniyah",
    operator: "KR Group",
    depart: "14:30",
    arrive: "17:50",
    durationMin: 200,
    seat: "Standard",
    sources: [{ source: "Station", usd: 11 }],
  },
  {
    kind: "bus",
    id: "cihan-ebl-doh",
    from: "erbil",
    to: "duhok",
    operator: "Erbil North Terminal",
    depart: "09:00",
    arrive: "11:20",
    durationMin: 140,
    seat: "VIP coach",
    sources: [{ source: "Station", usd: 12 }],
  },
  {
    kind: "bus",
    id: "garra-ebl-bgw",
    from: "erbil",
    to: "baghdad",
    operator: "Garra Transport",
    depart: "07:00",
    arrive: "12:40",
    durationMin: 340,
    seat: "VIP coach",
    sources: [
      { source: "Station", usd: 22 },
      { source: "Gesht", usd: 25 },
    ],
  },
  {
    kind: "bus",
    id: "garra-bgw-ebl",
    from: "baghdad",
    to: "erbil",
    operator: "Garra Transport",
    depart: "13:30",
    arrive: "19:10",
    durationMin: 340,
    seat: "VIP coach",
    sources: [{ source: "Station", usd: 22 }],
  },
  {
    kind: "bus",
    id: "najaf-karbala",
    from: "najaf",
    to: "karbala",
    operator: "Local shared taxi",
    depart: "Hourly",
    arrive: "+1h",
    durationMin: 70,
    seat: "Shared sedan",
    sources: [{ source: "Garage", usd: 6 }],
  },
  {
    kind: "bus",
    id: "bgw-njf",
    from: "baghdad",
    to: "najaf",
    operator: "Al-Najaf Garage",
    depart: "08:30",
    arrive: "11:00",
    durationMin: 150,
    seat: "Coach",
    sources: [{ source: "Garage", usd: 9 }],
  },
  {
    kind: "bus",
    id: "bgw-bsr",
    from: "baghdad",
    to: "basra",
    operator: "South Line",
    depart: "06:30",
    arrive: "13:15",
    durationMin: 405,
    seat: "VIP coach",
    sources: [{ source: "Station", usd: 18 }],
  },
  {
    kind: "bus",
    id: "ebl-mosul",
    from: "erbil",
    to: "mosul",
    operator: "North Garage",
    depart: "08:00",
    arrive: "10:30",
    durationMin: 150,
    seat: "Minibus",
    sources: [{ source: "Garage", usd: 8 }],
  },
  {
    kind: "bus",
    id: "doh-zakho",
    from: "duhok",
    to: "zakho",
    operator: "Khabur Line",
    depart: "Hourly",
    arrive: "+1h",
    durationMin: 70,
    seat: "Shared taxi",
    sources: [{ source: "Garage", usd: 5 }],
  },
  {
    kind: "bus",
    id: "isu-halabja",
    from: "sulaymaniyah",
    to: "halabja",
    operator: "Hawraman Garage",
    depart: "09:00",
    arrive: "10:40",
    durationMin: 100,
    seat: "Minibus",
    sources: [{ source: "Garage", usd: 6 }],
  },
  {
    kind: "bus",
    id: "obilet-ist-ebl",
    from: "istanbul",
    to: "erbil",
    operator: "Best Van / Obilet",
    depart: "18:00",
    arrive: "+22h",
    durationMin: 1320,
    seat: "VIP 1+1 night coach",
    sources: [
      { source: "Obilet", usd: 55 },
      { source: "Rama Travel", usd: 62 },
    ],
  },
  {
    kind: "bus",
    id: "rama-doh-diy",
    from: "duhok",
    to: "istanbul",
    operator: "Rama Travel",
    depart: "16:00",
    arrive: "+20h",
    durationMin: 1200,
    seat: "VIP coach",
    sources: [{ source: "Rama Travel", usd: 58 }],
  },
  {
    kind: "bus",
    id: "east-isu-ebl",
    from: "sulaymaniyah",
    to: "erbil",
    operator: "Erbil Garaj",
    depart: "08:30",
    arrive: "11:40",
    durationMin: 190,
    seat: "VIP coach",
    sources: [{ source: "Station", usd: 14 }],
  },
  {
    kind: "bus",
    id: "north-doh-ebl",
    from: "duhok",
    to: "erbil",
    operator: "Erbil North Terminal",
    depart: "10:00",
    arrive: "12:20",
    durationMin: 140,
    seat: "VIP coach",
    sources: [{ source: "Station", usd: 12 }],
  },
  {
    kind: "bus",
    id: "isu-doh",
    from: "sulaymaniyah",
    to: "duhok",
    operator: "Shared VIP",
    depart: "07:30",
    arrive: "12:30",
    durationMin: 300,
    seat: "Minibus",
    sources: [{ source: "Garage", usd: 18 }],
  },
];

export const packages: PackageOffer[] = [
  {
    kind: "package",
    id: "krg-classic",
    title: "Kurdistan citadel circuit",
    cities: ["erbil", "rawanduz", "sulaymaniyah"],
    nights: 6,
    priceUsd: 890,
    includes: ["Driver-guide", "Mid-range hotels", "Hamilton Road day"],
    season: "Mar–May, Sep–Nov",
  },
  {
    kind: "package",
    id: "north-high",
    title: "High north: Duhok & Amedi",
    cities: ["erbil", "duhok", "amedi"],
    nights: 5,
    priceUsd: 760,
    includes: ["Private car", "Mountain guesthouse", "Lalish option"],
    season: "Apr–Jun, Sep–Oct",
  },
  {
    kind: "package",
    id: "two-iraqs",
    title: "Erbil to Baghdad",
    cities: ["erbil", "baghdad"],
    nights: 7,
    priceUsd: 1280,
    includes: ["Domestic flight", "Fixer in Baghdad", "Museum day"],
    season: "Oct–Apr",
  },
  {
    kind: "package",
    id: "mesopotamia",
    title: "Baghdad, Babylon & the south",
    cities: ["baghdad", "najaf", "basra"],
    nights: 8,
    priceUsd: 1490,
    includes: ["Permits", "Private transport", "4-star hotels"],
    season: "Nov–Mar",
  },
  {
    kind: "package",
    id: "shrine",
    title: "Najaf & Karbala",
    cities: ["najaf", "karbala"],
    nights: 4,
    priceUsd: 540,
    includes: ["Airport meet", "Walking hotels", "Shared transfers"],
    season: "Year-round, surge in Muharram",
  },
  {
    kind: "package",
    id: "nineveh",
    title: "Erbil and Mosul",
    cities: ["erbil", "mosul"],
    nights: 5,
    priceUsd: 980,
    includes: ["Local historian", "Site permissions", "Driver"],
    season: "Oct–Apr",
  },
  {
    kind: "package",
    id: "zmt-week",
    title: "Zagros Mountain Trail week",
    cities: ["akre", "rawanduz", "choman"],
    nights: 8,
    priceUsd: 1680,
    includes: ["Village stays", "Stage guides", "Erbil transfers"],
    season: "Apr–Jun, Sep–Oct",
  },
  {
    kind: "package",
    id: "hawraman-days",
    title: "Hawraman and Halabja",
    cities: ["sulaymaniyah", "halabja", "hawraman"],
    nights: 4,
    priceUsd: 620,
    includes: ["Driver-guide", "Village house", "Ahmad Awa stop"],
    season: "Mar–Jun, Sep–Nov",
  },
  {
    kind: "package",
    id: "friday-empty",
    title: "Erbil Friday empty-out",
    cities: ["erbil", "shaqlawa", "dukan"],
    nights: 2,
    priceUsd: 280,
    includes: ["Villa Friday–Saturday", "Driver", "Market shop"],
    season: "Apr–Jun, Sep–Nov",
  },
  {
    kind: "package",
    id: "care-erbil",
    title: "Erbil care week",
    cities: ["erbil"],
    nights: 6,
    priceUsd: 2100,
    includes: ["Hospital letter", "Ankawa apartment", "Airport meet"],
    season: "Year-round",
  },
  {
    kind: "package",
    id: "care-turkey",
    title: "Istanbul care week",
    cities: ["erbil", "istanbul"],
    nights: 8,
    priceUsd: 3600,
    includes: ["Hospital letter", "EBL–IST", "Hotel at campus", "Arabic/Kurdish desk"],
    season: "Year-round",
  },
  {
    kind: "package",
    id: "care-jordan",
    title: "Amman oncology week",
    cities: ["baghdad", "amman"],
    nights: 10,
    priceUsd: 3400,
    includes: ["KHCC file", "BGW–AMM", "Hotel", "Arabic coordinator"],
    season: "Year-round",
  },
  {
    kind: "package",
    id: "care-iran",
    title: "Tehran fertility / cardiac",
    cities: ["sulaymaniyah", "tehran"],
    nights: 10,
    priceUsd: 1950,
    includes: ["Land or IKA hop", "Apartment", "Cash desk", "Kurdish coordinator"],
    season: "Year-round",
  },
  {
    kind: "package",
    id: "care-india",
    title: "Delhi e-Medical trip",
    cities: ["erbil", "delhi"],
    nights: 12,
    priceUsd: 2900,
    includes: ["Hospital letter", "e-Medical visa packet", "Via DXB", "Arabic desk"],
    season: "Year-round",
  },
];

export const roadNotes: Record<
  string,
  { road: "highway" | "mountain" | "mixed"; checkpoints: number; notes: string[]; waypoints: string[] }
> = {
  "erbil-sulaymaniyah": {
    road: "mixed",
    checkpoints: 2,
    notes: [
      "Paved the whole way. The last hour climbs into the Zagros.",
      "Winter fog on the ridge can add 30–40 minutes.",
    ],
    waypoints: ["Koya", "Dukan lake"],
  },
  "erbil-duhok": {
    road: "highway",
    checkpoints: 1,
    notes: ["Fast dual carriageway. The easiest drive in the KRG."],
    waypoints: ["Mosul road junction"],
  },
  "erbil-baghdad": {
    road: "highway",
    checkpoints: 6,
    notes: [
      "Federal crossing south of Kirkuk. Carry the Iraq e-visa, not only the KRG stamp.",
      "Leave at dawn. Do not drive this after dark.",
    ],
    waypoints: ["Kirkuk bypass", "Samarra turnoff"],
  },
  "erbil-mosul": {
    road: "highway",
    checkpoints: 4,
    notes: ["Short but checkpoint-heavy. Go with a local driver the first time."],
    waypoints: ["Kalak", "East Mosul"],
  },
  "erbil-rawanduz": {
    road: "mountain",
    checkpoints: 1,
    notes: ["Hamilton Road is the point of the drive. Avoid after ice warnings."],
    waypoints: ["Shaqlawa", "Korek", "Gali Ali Beg"],
  },
  "duhok-amedi": {
    road: "mountain",
    checkpoints: 1,
    notes: ["Switchbacks into the mesa. Beautiful, slow, and fully paved."],
    waypoints: ["Sarsing"],
  },
  "duhok-zakho": {
    road: "highway",
    checkpoints: 2,
    notes: ["The Turkey land-crossing road. Expect queues at Ibrahim Khalil."],
    waypoints: ["Ibrahim Khalil"],
  },
  "baghdad-najaf": {
    road: "highway",
    checkpoints: 3,
    notes: ["Busy on Thursday evenings and around Arbaeen. Shared taxis are constant."],
    waypoints: ["Mahmudiyah", "Hilla"],
  },
  "najaf-karbala": {
    road: "highway",
    checkpoints: 2,
    notes: ["About an hour. During Arbaeen the road is a walking route — use the pilgrim corridor."],
    waypoints: ["Between the two shrines road"],
  },
  "baghdad-basra": {
    road: "highway",
    checkpoints: 5,
    notes: ["Long southern highway. Fly if you can; drive only in daylight."],
    waypoints: ["Kut", "Nasiriyah"],
  },
  "sulaymaniyah-halabja": {
    road: "mixed",
    checkpoints: 1,
    notes: ["Easy day trip. Combine with Ahmad Awa if the weather is clear."],
    waypoints: ["Sirwan"],
  },
  "erbil-shaqlawa": {
    road: "mixed",
    checkpoints: 1,
    notes: ["Fifty minutes if you leave before Friday noon. The climb starts after the last Erbil ring."],
    waypoints: ["Kasnazan"],
  },
  "erbil-dukan": {
    road: "mixed",
    checkpoints: 2,
    notes: ["The Slemani road as far as the lake. Friday traffic stacks at the last dam bend."],
    waypoints: ["Koya", "Dukan dam"],
  },
  "sulaymaniyah-dukan": {
    road: "highway",
    checkpoints: 1,
    notes: ["Shorter than from Erbil. The usual Slemani Friday house run."],
    waypoints: ["Dokan town"],
  },
  "sulaymaniyah-hawraman": {
    road: "mountain",
    checkpoints: 2,
    notes: ["Halabja then the climb to Tawela. Border district — stay on the used road."],
    waypoints: ["Halabja", "Tawela"],
  },
  "erbil-korek": {
    road: "mountain",
    checkpoints: 1,
    notes: ["Hamilton Road to the resort gate. Ice closes the last climb some March mornings."],
    waypoints: ["Shaqlawa", "Gali Ali Beg"],
  },
};
