import type { CareOffer, HikeOffer, StayOffer } from "./types";

export const hikes: HikeOffer[] = [
  {
    kind: "hike",
    id: "hike-gali",
    trail: "Gali Ali Beg waterfall walk",
    city: "gali-ali-beg",
    bases: ["erbil", "rawanduz", "korek"],
    grade: "easy",
    km: 4,
    hours: 2.5,
    season: "Mar–Jun, Sep–Nov",
    priceUsd: 45,
    includes: ["Driver-guide", "Tea stop", "Pickup in Erbil"],
    note: "The classic Hamilton Road day. Paved approach, short trail to the falls, busy on Fridays.",
  },
  {
    kind: "hike",
    id: "hike-korek",
    trail: "Korek ridge & cable car",
    city: "korek",
    bases: ["erbil", "rawanduz"],
    grade: "moderate",
    km: 8,
    hours: 4,
    season: "Apr–Oct",
    priceUsd: 72,
    includes: ["Cable-car ticket", "Ridge guide", "Picnic"],
    note: "Ride up, walk the ridge. Snow lingers into April; summer afternoons are exposed.",
  },
  {
    kind: "hike",
    id: "hike-halgurd",
    trail: "Halgurd approach from Choman",
    city: "choman",
    bases: ["erbil", "rawanduz"],
    grade: "hard",
    km: 16,
    hours: 9,
    season: "Jun–Sep",
    priceUsd: 180,
    includes: ["Mountain guide", "Permits", "Overnight option"],
    note: "The serious KRG peak. Not a casual Friday. Weather turns fast above 3,000 m.",
  },
  {
    kind: "hike",
    id: "hike-shaqlawa",
    trail: "Safeen hillside paths",
    city: "shaqlawa",
    bases: ["erbil"],
    grade: "easy",
    km: 5,
    hours: 2,
    season: "Year-round",
    priceUsd: 28,
    includes: ["Local walker", "Orchard stop"],
    note: "Gentle terraces above town. Pair with a villa night if you do not want the Erbil traffic back.",
  },
  {
    kind: "hike",
    id: "hike-ahmad",
    trail: "Ahmad Awa waterfall valley",
    city: "ahmad-awa",
    bases: ["sulaymaniyah", "halabja"],
    grade: "easy",
    km: 3,
    hours: 1.5,
    season: "Mar–Jun",
    priceUsd: 32,
    includes: ["Slemani pickup", "Picnic spot"],
    note: "Spring water and Friday crowds. Go early or on a weekday.",
  },
  {
    kind: "hike",
    id: "hike-amedi",
    trail: "Amedi mesa circuit",
    city: "amedi",
    bases: ["duhok"],
    grade: "moderate",
    km: 7,
    hours: 3.5,
    season: "Apr–Nov",
    priceUsd: 55,
    includes: ["Duhok driver", "Citadel walk"],
    note: "Around the mesa rim and down to the canyon tea stands. Fog after rain.",
  },
  {
    kind: "hike",
    id: "hike-akre",
    trail: "Akre Nowruz ridge",
    city: "akre",
    bases: ["duhok", "erbil"],
    grade: "moderate",
    km: 6,
    hours: 3,
    season: "Mar–May, Oct",
    priceUsd: 48,
    includes: ["Hill guide", "Town breakfast"],
    note: "The stepped town is the trailhead. Nowruz week is a festival, not a hike.",
  },
  {
    kind: "hike",
    id: "hike-rawanduz",
    trail: "Rawanduz canyon viewpoints",
    city: "rawanduz",
    bases: ["erbil", "korek"],
    grade: "easy",
    km: 5,
    hours: 2.5,
    season: "Mar–Nov",
    priceUsd: 40,
    includes: ["Hamilton Road stops", "Driver"],
    note: "Viewpoints more than wilderness. Combine with Gali Ali Beg in one long day.",
  },
];

export const stays: StayOffer[] = [
  {
    kind: "stay",
    id: "stay-shaqlawa-garden",
    city: "shaqlawa",
    name: "Safeen garden villa",
    type: "villa",
    area: "Upper Shaqlawa",
    guests: 8,
    nightlyUsd: 160,
    driveFrom: "50 min from Erbil",
    amenities: ["Garden", "BBQ", "Two kitchens", "Parking"],
    note: "The default Erbil Friday house. Book Thursday night if you want Saturday quiet.",
  },
  {
    kind: "stay",
    id: "stay-shaqlawa-apt",
    city: "shaqlawa",
    name: "Orchard apartment",
    type: "apartment",
    area: "Town centre",
    guests: 4,
    nightlyUsd: 72,
    driveFrom: "50 min from Erbil",
    amenities: ["Kitchen", "Balcony", "Walk to souq"],
    note: "Walk to dinner. No garden, less generator noise than the big villas.",
  },
  {
    kind: "stay",
    id: "stay-dukan-lake",
    city: "dukan",
    name: "Lake terrace house",
    type: "villa",
    area: "Dukan shore",
    guests: 10,
    nightlyUsd: 210,
    driveFrom: "1h 40m from Erbil · 1h from Slemani",
    amenities: ["Lake view", "Jetty", "AC", "Cook optional"],
    note: "Summer weekends sell out. Confirm water and generator before you transfer the deposit.",
  },
  {
    kind: "stay",
    id: "stay-korek-chalet",
    city: "korek",
    name: "Korek ridge chalet",
    type: "chalet",
    area: "Resort ridge",
    guests: 6,
    nightlyUsd: 190,
    driveFrom: "2h from Erbil",
    amenities: ["Fireplace", "Cable car", "Mountain view"],
    note: "Cold at night even in May. The point is the altitude, not a city kitchen.",
  },
  {
    kind: "stay",
    id: "stay-rawanduz",
    city: "rawanduz",
    name: "Gorge-view villa",
    type: "villa",
    area: "Rawanduz canyon",
    guests: 8,
    nightlyUsd: 145,
    driveFrom: "1h 50m from Erbil",
    amenities: ["Terrace", "BBQ", "Parking"],
    note: "Best as a two-night Hamilton Road base, not a one-night dash.",
  },
  {
    kind: "stay",
    id: "stay-amedi",
    city: "amedi",
    name: "Mesa stone house",
    type: "chalet",
    area: "Old Amedi",
    guests: 5,
    nightlyUsd: 95,
    driveFrom: "1h 20m from Duhok",
    amenities: ["Old-town walk", "Heater", "Breakfast"],
    note: "Quiet after tour buses leave. Winter heating is the question to ask.",
  },
  {
    kind: "stay",
    id: "stay-akre",
    city: "akre",
    name: "Stepped-town apartment",
    type: "apartment",
    area: "Akre hillside",
    guests: 4,
    nightlyUsd: 68,
    driveFrom: "1h 30m from Duhok",
    amenities: ["View terrace", "Kitchen"],
    note: "Nowruz week triples the price. Other weekends it is a sleepy overnight.",
  },
  {
    kind: "stay",
    id: "stay-erbil-ankawa",
    city: "erbil",
    name: "Ankawa weekend apartment",
    type: "apartment",
    area: "Ankawa",
    guests: 4,
    nightlyUsd: 85,
    driveFrom: "In town",
    amenities: ["Kitchen", "Late restaurants", "Parking"],
    note: "For visitors who want a city Friday, not a mountain drive.",
  },
  {
    kind: "stay",
    id: "stay-slemani",
    city: "sulaymaniyah",
    name: "Salim Street apartment",
    type: "apartment",
    area: "Salim Street",
    guests: 3,
    nightlyUsd: 70,
    driveFrom: "In town",
    amenities: ["Walk to cafes", "Kitchen"],
    note: "The Slemani weekend is walking, not a villa. Use this as the city base.",
  },
  {
    kind: "stay",
    id: "stay-baghdad",
    city: "baghdad",
    name: "Jadriya river apartment",
    type: "apartment",
    area: "Jadriya",
    guests: 4,
    nightlyUsd: 110,
    driveFrom: "In town",
    amenities: ["Generator", "Doorman", "Kitchen"],
    note: "A domestic Baghdad weekend. Confirm the building generator and the driver’s hours.",
  },
  {
    kind: "stay",
    id: "stay-duhok",
    city: "duhok",
    name: "Valley family villa",
    type: "villa",
    area: "Duhok bowl",
    guests: 9,
    nightlyUsd: 130,
    driveFrom: "In town · 2h 20m from Erbil",
    amenities: ["Garden", "Two living rooms", "Parking"],
    note: "Family Friday house. Combine with Amedi if you have a second night.",
  },
  {
    kind: "stay",
    id: "stay-hawraman",
    city: "hawraman",
    name: "Tawela stone house",
    type: "chalet",
    area: "Tawela",
    guests: 6,
    nightlyUsd: 85,
    driveFrom: "2h from Slemani · 1h from Halabja",
    amenities: ["Village walk", "Terrace", "Breakfast"],
    note: "A Hawraman weekend, not a villa farm. Book through a Halabja fixer.",
  },
  {
    kind: "stay",
    id: "stay-sarsing",
    city: "sarsing",
    name: "Sarsing hill guesthouse",
    type: "chalet",
    area: "Sarsing",
    guests: 5,
    nightlyUsd: 70,
    driveFrom: "1h from Duhok",
    amenities: ["Cooler air", "Garden"],
    note: "The Gara weekend base. Quieter than Amedi on festival days.",
  },
  {
    kind: "stay",
    id: "stay-zawita",
    city: "zawita",
    name: "Zawita pine cabin",
    type: "chalet",
    area: "Zawita forest",
    guests: 4,
    nightlyUsd: 65,
    driveFrom: "30 min from Duhok",
    amenities: ["Forest", "Parking"],
    note: "Walk the signed trail in the morning, drive back for dinner in Duhok.",
  },
];

export const care: CareOffer[] = [
  {
    kind: "care",
    id: "care-par-cardio",
    city: "erbil",
    hospital: "PAR Hospital",
    specialty: "Cardiology",
    wait: "Consult in 2–4 days",
    nights: 4,
    priceUsd: 1850,
    includes: ["Specialist consult", "Hotel 3 nights", "Airport transfer", "Kurdish/English coordinator"],
    languages: ["Kurdish", "Arabic", "English"],
    note: "The usual first stop for cardiac workups arriving into EBL. Ask for the written quote before imaging.",
    corridor: "home",
  },
  {
    kind: "care",
    id: "care-cmc-ortho",
    city: "erbil",
    hospital: "CMC",
    specialty: "Orthopedics",
    wait: "Consult this week",
    nights: 5,
    priceUsd: 1640,
    includes: ["Clinic visit", "Physio plan", "Ankawa hotel", "Driver"],
    languages: ["Kurdish", "Arabic", "English"],
    note: "Sports and joint work. Pair with an Ankawa apartment if family is traveling with you.",
    corridor: "home",
  },
  {
    kind: "care",
    id: "care-zheen",
    city: "erbil",
    hospital: "Zheen International",
    specialty: "Fertility",
    wait: "Intake in 3–7 days",
    nights: 7,
    priceUsd: 2420,
    includes: ["Intake consult", "Apartment week", "Transfer", "Translator"],
    languages: ["Kurdish", "Arabic", "English", "Persian"],
    note: "Common inbound corridor from Iran and the Gulf. Confirm which tests you must bring.",
    corridor: "home",
  },
  {
    kind: "care",
    id: "care-shar",
    city: "erbil",
    hospital: "Shar Hospital",
    specialty: "Oncology",
    wait: "Board review in 1 week",
    nights: 6,
    priceUsd: 2100,
    includes: ["Records review", "Hotel", "ISU or EBL transfer", "Coordinator"],
    languages: ["Kurdish", "Arabic", "English"],
    note: "Erbil 100m, not Slemani. Confirm the campus before you book the hotel.",
    corridor: "home",
  },
  {
    kind: "care",
    id: "care-faruk",
    city: "sulaymaniyah",
    hospital: "Faruk Medical City",
    specialty: "Dental & cosmetic",
    wait: "Next-week slots",
    nights: 3,
    priceUsd: 980,
    includes: ["Consult", "Hotel 2 nights", "City transfer"],
    languages: ["Kurdish", "Arabic", "English", "Turkish"],
    note: "Shorter stays. Get the treatment plan in writing; revisions are where bills grow.",
    corridor: "home",
  },
  {
    kind: "care",
    id: "care-ibnsina",
    city: "baghdad",
    hospital: "Ibn Sina",
    specialty: "General & surgical",
    wait: "Referral first",
    nights: 5,
    priceUsd: 1560,
    includes: ["Consultant", "Karada hotel", "Driver", "Federal visa note"],
    languages: ["Arabic", "English"],
    note: "Federal e-visa before you fly. A coordinator matters more here than in Erbil.",
    corridor: "home",
  },
  {
    kind: "care",
    id: "care-medcity",
    city: "baghdad",
    hospital: "Medical City",
    specialty: "Complex referral",
    wait: "Depends on specialty",
    nights: 6,
    priceUsd: 1320,
    includes: ["Referral packet", "Hotel", "Fixer"],
    languages: ["Arabic", "English"],
    note: "Teaching-hospital corridor. Not a walk-in medical-tourism desk — bring records.",
    corridor: "home",
  },
  {
    kind: "care",
    id: "care-acibadem",
    city: "istanbul",
    hospital: "Acıbadem",
    specialty: "Multi-specialty outbound",
    wait: "International desk, 3–5 days",
    nights: 6,
    priceUsd: 3200,
    includes: ["Hospital letter", "Hotel near clinic", "IST meet", "Arabic/Kurdish interpreter"],
    languages: ["Turkish", "English", "Arabic", "Kurdish"],
    note: "The usual outbound hop from the KRG when the case needs a larger campus.",
    corridor: "turkey",
    visa: "Confirm the current Iraqi e-visa for Turkey.",
    hop: "Daily EBL–IST. Hospital international desk meets the flight.",
  },
  {
    kind: "care",
    id: "care-abdali",
    city: "amman",
    hospital: "Abdali Hospital",
    specialty: "Cardiac & oncology",
    wait: "4–6 days",
    nights: 5,
    priceUsd: 2780,
    includes: ["Consult", "Hotel", "AMM transfer", "Arabic coordinator"],
    languages: ["Arabic", "English"],
    note: "Shorter flight than Istanbul for Baghdad and Basra patients.",
    corridor: "jordan",
    visa: "Jordan visa for Iraqi passports — start it with the hospital letter.",
    hop: "Royal Jordanian from BGW or EBL.",
  },
  {
    kind: "care",
    id: "care-aster",
    city: "dubai",
    hospital: "Aster & city clinics",
    specialty: "Diagnostics & second opinion",
    wait: "48–72 hours",
    nights: 4,
    priceUsd: 2450,
    includes: ["Imaging package", "Hotel", "DXB transfer"],
    languages: ["Arabic", "English", "Hindi"],
    note: "Used for fast imaging and second reads, then home. Not the cheapest lab.",
    visa: "UAE visa / transit as required. This is a diagnostics hop, not a full India trip.",
    hop: "flydubai or Emirates into DXB.",
  },
  {
    kind: "care",
    id: "care-memorial",
    city: "istanbul",
    hospital: "Memorial Şişli",
    specialty: "Oncology & transplant follow-up",
    wait: "International desk, 4–7 days",
    nights: 8,
    priceUsd: 3600,
    includes: ["Records review", "Hotel near campus", "IST meet", "Arabic coordinator"],
    languages: ["Turkish", "English", "Arabic", "Kurdish"],
    note: "A common second campus when Acıbadem is full. Written plan before you fly.",
    corridor: "turkey",
    visa: "Confirm the current Iraqi e-visa for Turkey.",
    hop: "Daily EBL–IST.",
  },
  {
    kind: "care",
    id: "care-medipol",
    city: "istanbul",
    hospital: "Medipol Mega",
    specialty: "Cardiac surgery",
    wait: "5–8 days",
    nights: 9,
    priceUsd: 4100,
    includes: ["Surgical consult", "ICU plan", "Hotel for companion", "Interpreter"],
    languages: ["Turkish", "English", "Arabic"],
    note: "Large campus, long stay. A companion should travel. Quote in writing.",
    corridor: "turkey",
    visa: "Confirm the current Iraqi e-visa for Turkey.",
    hop: "Daily EBL–IST.",
  },
  {
    kind: "care",
    id: "care-ankara-guven",
    city: "ankara",
    hospital: "Güven Hospital",
    specialty: "Multi-specialty",
    wait: "International desk, one week",
    nights: 7,
    priceUsd: 2950,
    includes: ["Consult", "Hotel", "ESB transfer"],
    languages: ["Turkish", "English", "Arabic"],
    note: "Quieter than Istanbul. Useful when the specialist sits in Ankara, not on the Bosphorus.",
    corridor: "turkey",
    visa: "Same Turkey visa as Istanbul.",
    hop: "Usually IST then a domestic hop, or a rare EBL–ESB.",
  },
  {
    kind: "care",
    id: "care-khcc",
    city: "amman",
    hospital: "King Hussein Cancer Center",
    specialty: "Oncology",
    wait: "Board review after records",
    nights: 10,
    priceUsd: 3400,
    includes: ["Records board", "Hotel near KHCC", "AMM transfer", "Arabic coordinator"],
    languages: ["Arabic", "English"],
    note: "The regional oncology campus Iraqi families name first. Not a walk-in. Send records before you buy the ticket.",
    corridor: "jordan",
    visa: "Jordan visa + hospital letter.",
    hop: "Royal Jordanian from Baghdad is the usual south-Iraq hop.",
  },
  {
    kind: "care",
    id: "care-istishari",
    city: "amman",
    hospital: "Istishari Hospital",
    specialty: "Cardiac & general",
    wait: "4–6 days",
    nights: 6,
    priceUsd: 2680,
    includes: ["Consult", "Hotel", "AMM transfer"],
    languages: ["Arabic", "English"],
    note: "Private Amman campus. Arabic the whole way — the reason families skip Istanbul.",
    corridor: "jordan",
    visa: "Jordan visa for Iraqi passports.",
    hop: "RJ from BGW or EBL.",
  },
  {
    kind: "care",
    id: "care-royan",
    city: "tehran",
    hospital: "Royan Institute",
    specialty: "Fertility",
    wait: "Intake after file review",
    nights: 10,
    priceUsd: 1850,
    includes: ["File review", "Apartment week", "IKA or land meet", "Persian/Kurdish coordinator"],
    languages: ["Persian", "Kurdish", "Arabic", "English"],
    note: "The fertility campus Iraqi and Kurdish couples already know. Bring prior labs. Cash, not cards.",
    corridor: "iran",
    visa: "Iraqis often visa-on-arrival. Confirm before the crossing.",
    hop: "Land from Slemani (Bashmakh) or IKA via Istanbul.",
  },
  {
    kind: "care",
    id: "care-thc",
    city: "tehran",
    hospital: "Tehran Heart Center",
    specialty: "Cardiology",
    wait: "1 week after records",
    nights: 8,
    priceUsd: 2100,
    includes: ["Consult", "Hotel", "Coordinator"],
    languages: ["Persian", "English", "Arabic"],
    note: "Teaching-hospital cardiac. Cheaper than Istanbul. Sanctions mean cash and a fixer who has done this corridor.",
    corridor: "iran",
    visa: "Confirm visa-on-arrival the week you travel.",
    hop: "IKA, or overland if you are already in the KRG.",
  },
  {
    kind: "care",
    id: "care-tabriz",
    city: "tabriz",
    hospital: "Imam Reza Tabriz",
    specialty: "General & cardiac",
    wait: "Local coordinator, a few days",
    nights: 6,
    priceUsd: 1450,
    includes: ["Consult", "Hotel", "Border meet"],
    languages: ["Persian", "Azeri", "Kurdish", "Turkish"],
    note: "The close Iran campus from Duhok and Slemani. A land day, not a flight. Do not improvise the crossing.",
    corridor: "iran",
    visa: "Land crossing + visa-on-arrival — check that morning.",
    hop: "Haji Omaran or Bashmakh, then Tabriz.",
  },
  {
    kind: "care",
    id: "care-medanta",
    city: "delhi",
    hospital: "Medanta",
    specialty: "Cardiac & multi-specialty",
    wait: "e-Medical visa first, then a slot",
    nights: 12,
    priceUsd: 2800,
    includes: ["Hospital letter", "Visa packet", "Hotel", "DEL meet", "Arabic desk"],
    languages: ["English", "Hindi", "Arabic"],
    note: "Often 50–70% of a Turkey quote for the same surgery. The letter comes before the ticket. Two weeks, not a long weekend.",
    corridor: "india",
    visa: "India e-Medical visa. Hospital letter first.",
    hop: "Via Dubai or Doha. Rarely nonstop.",
  },
  {
    kind: "care",
    id: "care-fortis",
    city: "delhi",
    hospital: "Fortis",
    specialty: "Oncology & ortho",
    wait: "After e-Medical visa",
    nights: 11,
    priceUsd: 2550,
    includes: ["Letter", "Hotel", "DEL transfer", "Interpreter"],
    languages: ["English", "Arabic"],
    note: "Second Delhi campus. Same visa order: letter, visa, then flight.",
    corridor: "india",
    visa: "India e-Medical visa.",
    hop: "Via DXB or DOH.",
  },
  {
    kind: "care",
    id: "care-apollo",
    city: "chennai",
    hospital: "Apollo Chennai",
    specialty: "Cardiac & oncology",
    wait: "International desk after visa",
    nights: 14,
    priceUsd: 2700,
    includes: ["Hospital letter", "Hotel on campus road", "MAA meet"],
    languages: ["English", "Arabic", "Tamil"],
    note: "South India campus. Longer flight than Delhi. Go when the named surgeon is in Chennai, not because the city is cheaper.",
    corridor: "india",
    visa: "India e-Medical visa. Letter first.",
    hop: "Via Gulf hubs into MAA.",
  },
];
