import type { Place } from "./types";

export const places: Place[] = [
  {
    id: "erbil",
    name: "Erbil",
    localName: "Hewlêr",
    country: "Kurdistan Region",
    region: "krg",
    iata: "EBL",
    lat: 36.1911,
    lng: 44.0092,
    blurb: "The citadel city and the easiest air gateway into the Kurdistan Region.",
    image: "/destinations/erbil.jpg",
    video: "/destinations/erbil.mp4",
    featured: true,
    focus: ["weekend", "medical"],
  },
  {
    id: "sulaymaniyah",
    name: "Sulaymaniyah",
    localName: "Slemani",
    country: "Kurdistan Region",
    region: "krg",
    iata: "ISU",
    lat: 35.561,
    lng: 45.43,
    blurb: "Cultural capital of the KRG — mountains, cafes, and a second international airport.",
    image: "/destinations/sulaymaniyah.jpg",
    video: "/destinations/sulaymaniyah.mp4",
    featured: true,
    focus: ["hike", "weekend", "medical"],
  },
  {
    id: "duhok",
    name: "Duhok",
    localName: "Dihok",
    country: "Kurdistan Region",
    region: "krg",
    lat: 36.867,
    lng: 42.988,
    blurb: "Northern mountain city, close to Zakho and the Turkish border road.",
    image: "/destinations/duhok.jpg",
    featured: true,
    focus: ["hike", "weekend"],
  },
  {
    id: "baghdad",
    name: "Baghdad",
    localName: "بغداد",
    country: "Iraq",
    region: "federal",
    iata: "BGW",
    lat: 33.3152,
    lng: 44.3661,
    blurb: "The Tigris capital — museums, river cafes, and the main federal gateway.",
    image: "/destinations/baghdad.jpg",
    video: "/destinations/baghdad.mp4",
    featured: true,
    focus: ["weekend", "medical"],
  },
  {
    id: "najaf",
    name: "Najaf",
    localName: "النجف",
    country: "Iraq",
    region: "federal",
    iata: "NJF",
    lat: 32.0,
    lng: 44.34,
    blurb: "Shrine city and a major pilgrimage airport, a short drive from Karbala.",
    image: "/destinations/najaf.jpg",
    featured: true,
  },
  {
    id: "basra",
    name: "Basra",
    localName: "البصرة",
    country: "Iraq",
    region: "federal",
    iata: "BSR",
    lat: 30.508,
    lng: 47.78,
    blurb: "The southern port on the Shatt al-Arab — palms, canals, and Gulf flights.",
    image: "/destinations/basra.jpg",
    featured: true,
  },
  {
    id: "karbala",
    name: "Karbala",
    localName: "كربلاء",
    country: "Iraq",
    region: "federal",
    lat: 32.616,
    lng: 44.025,
    blurb: "Pilgrimage city. Most visitors fly into Najaf and continue by road.",
  },
  {
    id: "mosul",
    name: "Mosul",
    localName: "الموصل",
    country: "Iraq",
    region: "federal",
    lat: 36.34,
    lng: 43.13,
    blurb: "Nineveh’s city on the Tigris, reached overland from Erbil or Duhok.",
  },
  {
    id: "kirkuk",
    name: "Kirkuk",
    localName: "Kerkûk",
    country: "Iraq",
    region: "federal",
    iata: "KIK",
    lat: 35.47,
    lng: 44.39,
    blurb: "Oil city between Baghdad and the KRG, with a small airport and road links.",
  },
  {
    id: "zakho",
    name: "Zakho",
    localName: "Zaxo",
    country: "Kurdistan Region",
    region: "krg",
    lat: 37.144,
    lng: 42.687,
    blurb: "Border town on the Khabur, the usual land crossing from Turkey.",
  },
  {
    id: "amedi",
    name: "Amedi",
    localName: "Amêdî",
    country: "Kurdistan Region",
    region: "krg",
    lat: 37.092,
    lng: 43.487,
    blurb: "A mesa town in the high north — weekend drives from Duhok.",
    image: "/destinations/duhok.jpg",
    focus: ["hike", "weekend"],
  },
  {
    id: "rawanduz",
    name: "Rawanduz",
    localName: "Rewandiz",
    country: "Kurdistan Region",
    region: "krg",
    lat: 36.612,
    lng: 44.524,
    blurb: "Gorges, Hamilton Road, and the mountain weekend circuit from Erbil.",
    focus: ["hike", "weekend"],
  },
  {
    id: "halabja",
    name: "Halabja",
    localName: "Helebce",
    country: "Kurdistan Region",
    region: "krg",
    lat: 35.178,
    lng: 45.986,
    blurb: "Memorial city east of Sulaymaniyah, usually a day trip by car.",
    focus: ["hike"],
  },
  {
    id: "shaqlawa",
    name: "Shaqlawa",
    localName: "Şeqlawe",
    country: "Kurdistan Region",
    region: "krg",
    lat: 36.405,
    lng: 44.321,
    blurb: "Hill town 50 minutes from Erbil — orchards, weekend villas, easy walks.",
    image: "/destinations/shaqlawa.jpg",
    video: "/destinations/shaqlawa.mp4",
    focus: ["hike", "weekend"],
  },
  {
    id: "korek",
    name: "Korek",
    localName: "Korek",
    country: "Kurdistan Region",
    region: "krg",
    lat: 36.586,
    lng: 44.46,
    blurb: "Ridge above Rawanduz with a cable car, chalets, and high trails.",
    image: "/destinations/korek.jpg",
    video: "/destinations/korek.mp4",
    focus: ["hike", "weekend"],
  },
  {
    id: "gali-ali-beg",
    name: "Gali Ali Beg",
    localName: "Gelî Elî Beg",
    country: "Kurdistan Region",
    region: "krg",
    lat: 36.628,
    lng: 44.45,
    blurb: "The waterfall gorge on Hamilton Road — the KRG’s classic day hike.",
    image: "/destinations/gali-ali-beg.jpg",
    video: "/destinations/gali-ali-beg.mp4",
    focus: ["hike"],
  },
  {
    id: "dukan",
    name: "Dukan",
    localName: "Dukan",
    country: "Kurdistan Region",
    region: "krg",
    lat: 35.954,
    lng: 44.958,
    blurb: "Lake town between Erbil and Slemani — villas, swimming, Friday traffic.",
    image: "/destinations/dukan.jpg",
    video: "/destinations/dukan.mp4",
    focus: ["weekend"],
  },
  {
    id: "ahmad-awa",
    name: "Ahmad Awa",
    localName: "Ehmadawa",
    country: "Kurdistan Region",
    region: "krg",
    lat: 35.3,
    lng: 46.09,
    blurb: "Waterfall picnic valley east of Slemani, busy on Fridays in spring.",
    image: "/destinations/sulaymaniyah.jpg",
    focus: ["hike", "weekend"],
  },
  {
    id: "choman",
    name: "Choman",
    localName: "Çoman",
    country: "Kurdistan Region",
    region: "krg",
    lat: 36.637,
    lng: 44.885,
    blurb: "Gateway to Halgurd — the serious high-mountain trail in the KRG.",
    image: "/destinations/korek.jpg",
    focus: ["hike"],
  },
  {
    id: "akre",
    name: "Akre",
    localName: "Akré",
    country: "Kurdistan Region",
    region: "krg",
    lat: 36.741,
    lng: 43.893,
    blurb: "Stepped hillside town famous at Nowruz, a quiet overnight otherwise.",
    image: "/destinations/duhok.jpg",
    focus: ["hike", "weekend"],
  },
  {
    id: "istanbul",
    name: "Istanbul",
    localName: "İstanbul",
    country: "Turkey",
    region: "gateway",
    iata: "IST",
    lat: 41.0082,
    lng: 28.9784,
    blurb: "The busiest connecting city into Erbil, Baghdad, and Sulaymaniyah.",
    focus: ["medical"],
  },
  {
    id: "dubai",
    name: "Dubai",
    localName: "دبي",
    country: "UAE",
    region: "gateway",
    iata: "DXB",
    lat: 25.2048,
    lng: 55.2708,
    blurb: "Gulf hub for flydubai and Emirates into EBL, BGW, NJF, and BSR.",
    focus: ["medical"],
  },
  {
    id: "doha",
    name: "Doha",
    localName: "الدوحة",
    country: "Qatar",
    region: "gateway",
    iata: "DOH",
    lat: 25.2854,
    lng: 51.531,
    blurb: "Qatar Airways connections into Erbil and Baghdad.",
  },
  {
    id: "amman",
    name: "Amman",
    localName: "عمّان",
    country: "Jordan",
    region: "gateway",
    iata: "AMM",
    lat: 31.9539,
    lng: 35.9106,
    blurb: "Royal Jordanian and a common overland-adjacent Gulf hop.",
    focus: ["medical"],
  },
  {
    id: "london",
    name: "London",
    localName: "London",
    country: "United Kingdom",
    region: "gateway",
    iata: "LHR",
    lat: 51.47,
    lng: -0.4543,
    blurb: "One-stop European origin, usually via Istanbul or the Gulf.",
  },
  {
    id: "frankfurt",
    name: "Frankfurt",
    localName: "Frankfurt",
    country: "Germany",
    region: "gateway",
    iata: "FRA",
    lat: 50.0379,
    lng: 8.5622,
    blurb: "Lufthansa and FlyErbil seasonal links toward Erbil.",
  },
  {
    id: "cairo",
    name: "Cairo",
    localName: "القاهرة",
    country: "Egypt",
    region: "gateway",
    iata: "CAI",
    lat: 30.112,
    lng: 31.4,
    blurb: "EgyptAir and connecting traffic into Baghdad and Erbil.",
  },
  {
    id: "kuwait",
    name: "Kuwait City",
    localName: "الكويت",
    country: "Kuwait",
    region: "gateway",
    iata: "KWI",
    lat: 29.226,
    lng: 47.969,
    blurb: "Short Gulf hop to Basra, Najaf, and Baghdad.",
  },
  {
    id: "beirut",
    name: "Beirut",
    localName: "بيروت",
    country: "Lebanon",
    region: "gateway",
    iata: "BEY",
    lat: 33.8209,
    lng: 35.4884,
    blurb: "Levant connection, often via Amman or Istanbul.",
  },
];

export const placeById = Object.fromEntries(places.map((p) => [p.id, p])) as Record<
  string,
  Place
>;

export function getPlace(id: string): Place | undefined {
  return placeById[id];
}

export function searchPlaces(q: string, opts?: { exclude?: string; mode?: string }) {
  const query = q.trim().toLowerCase();
  const pool = placesForMode(opts?.mode);
  return pool.filter((p) => {
    if (opts?.exclude && p.id === opts.exclude) return false;
    if (!query) return true;
    return (
      p.name.toLowerCase().includes(query) ||
      p.localName.toLowerCase().includes(query) ||
      p.country.toLowerCase().includes(query) ||
      (p.iata && p.iata.toLowerCase().includes(query))
    );
  });
}

export function placesForMode(mode?: string) {
  if (mode === "hiking") return places.filter((p) => p.focus?.includes("hike"));
  if (mode === "weekends") return places.filter((p) => p.focus?.includes("weekend"));
  if (mode === "medical") return places.filter((p) => p.focus?.includes("medical"));
  return places;
}

export const featuredDestinations = places.filter((p) => p.featured);
export const localPlaces = places.filter((p) => p.region !== "gateway");
export const gatewayPlaces = places.filter((p) => p.region === "gateway");
export const hikeDestinations = places.filter((p) => p.focus?.includes("hike"));
export const weekendDestinations = places.filter((p) => p.focus?.includes("weekend"));
export const medicalDestinations = places.filter((p) => p.focus?.includes("medical"));
