/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForProvidersRouteImport } from './routes/for-providers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGeshtSplatRouteImport } from './routes/api/gesht/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProvidersRoute = ForProvidersRouteImport.update({
  id: '/for-providers',
  path: '/for-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeshtSplatRoute = ApiGeshtSplatRouteImport.update({
  id: '/api/gesht/$',
  path: '/api/gesht/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-providers': typeof ForProvidersRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gesht/$': typeof ApiGeshtSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-providers': typeof ForProvidersRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gesht/$': typeof ApiGeshtSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-providers': typeof ForProvidersRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gesht/$': typeof ApiGeshtSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/for-providers'
    | '/login'
    | '/search'
    | '/api/auth/$'
    | '/api/gesht/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/for-providers'
    | '/login'
    | '/search'
    | '/api/auth/$'
    | '/api/gesht/$'
  id:
    | '__root__'
    | '/'
    | '/for-providers'
    | '/login'
    | '/search'
    | '/api/auth/$'
    | '/api/gesht/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForProvidersRoute: typeof ForProvidersRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGeshtSplatRoute: typeof ApiGeshtSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-providers': {
      id: '/for-providers'
      path: '/for-providers'
      fullPath: '/for-providers'
      preLoaderRoute: typeof ForProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gesht/$': {
      id: '/api/gesht/$'
      path: '/api/gesht/$'
      fullPath: '/api/gesht/$'
      preLoaderRoute: typeof ApiGeshtSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForProvidersRoute: ForProvidersRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGeshtSplatRoute: ApiGeshtSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
